language: python
sudo: required
services:
  - docker

script:
# Requires external resources which may be flakey, so auto-retry once
- docker build -t omerodev-docker . || docker build -t omerodev-docker .
