---

- hosts: localhost
  tasks:

  - name: create postgres users
    become: yes
    become_user: postgres
    postgresql_user:
      encrypted: yes
      name: omero
      password: omero
      state: present

  - name: create postgres databases
    become: yes
    become_user: postgres
    postgresql_db:
      encoding: UTF-8
      name: omero
      owner: omero
      state: present

  - name: create default virtualenv
    become: yes
    become_user: build
    pip:
      name: omego
      state: latest
      virtualenv: /home/build/src/venv
      virtualenv_site_packages: yes
